// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class DeleteCmd extends Delete {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 3 ;

    public void execute () {
        
        super.execute();
    }

    public AstToken getDELETE () {
        
        return (AstToken) tok [0] ;
    }

    public One_rel_pred getOne_rel_pred () {
        
        return (One_rel_pred) arg [1] ;
    }

    public Rel_name getRel_name () {
        
        return (Rel_name) arg [0] ;
    }

    public AstToken getSEMI () {
        
        return (AstToken) tok [2] ;
    }

    public AstToken getWHERE () {
        
        return (AstToken) tok [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, false, true, false, true} ;
    }

    public DeleteCmd setParms
    (AstToken tok0, Rel_name arg0, AstToken tok1, One_rel_pred arg1, AstToken tok2)
    {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* DELETE */
        arg [0] = arg0 ;            /* Rel_name */
        tok [1] = tok1 ;            /* WHERE */
        arg [1] = arg1 ;            /* One_rel_pred */
        tok [2] = tok2 ;            /* SEMI */
        
        InitChildren () ;
        return (DeleteCmd) this ;
    }

}
