// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

public class Fld_decl_listElem extends AstListNode {

    public AstToken getCOMMA () {
        return (AstToken) tok [0] ;
    }

    public Field_decl getField_decl () {
        
        return (Field_decl) arg [0] ;
    }

    public Fld_decl_listElem setParms (AstToken tok0, Field_decl arg0) {
        
        tok = new AstToken [1] ;
        tok [0] = tok0 ;            /* COMMA */
        return setParms (arg0) ;    /* Field_decl */
    }

    public Fld_decl_listElem setParms (Field_decl arg0) {
        
        super.setParms (arg0) ;     /* Field_decl */
        return (Fld_decl_listElem) this ;
    }

}
