// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

import java.io.*;

public class ScriptCmd extends Script {

    final public static int ARG_LENGTH = 1 /* Kludge! */ ;
    final public static int TOK_LENGTH = 3 ;

    public void execute () {
        
        super.execute();
        BufferedReader       userInput = null;

        try {
//            userInput =  new BufferedReader( new FileReader(  ) );
            System.setIn(new FileInputStream(getSTRING_LITERAL().tokenName().replaceAll("^\"|\"$", "")));

//            InputStream stream = new ByteArrayInputStream("hellloooo;\n.\n".getBytes("UTF-8"));

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        System.out.println(userInput);
    }

    public AstToken getSCRIPT () {
        
        return (AstToken) tok [0] ;
    }

    public AstToken getSEMI () {
        
        return (AstToken) tok [2] ;
    }

    public AstToken getSTRING_LITERAL () {
        
        return (AstToken) tok [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, true, true} ;
    }

    public ScriptCmd setParms (AstToken tok0, AstToken tok1, AstToken tok2) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* SCRIPT */
        tok [1] = tok1 ;            /* STRING_LITERAL */
        tok [2] = tok2 ;            /* SEMI */
        
        InitChildren () ;
        return (ScriptCmd) this ;
    }

}
