// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.EnvironmentNotFoundException;
import minidb.je.ExecuteHelpers;

import java.util.ArrayList;

public class ShowDb extends Show {

    final public static int ARG_LENGTH = 1 /* Kludge! */ ;
    final public static int TOK_LENGTH = 2 ;

//    public static boolean findRelation(String relationName) {
//        return ExecuteHelpers.showAllRowsOfTable("relationDB", relationName, 0);
//    }

    private static String showAllRelations()
            throws DatabaseException {
        ArrayList<String> relations = ExecuteHelpers.getAllRowsOfTable("relationDB");
        StringBuffer displayString = new StringBuffer();
        for(int i = 0; i < relations.size(); i++) {
            String relationName = relations.get(i);
            displayString.append(ExecuteHelpers.getShowData(relationName));
            displayString.append("\n");
        }
        return displayString.toString();
    }


    public void execute () {
        
        super.execute();

        try {
            System.out.println(showAllRelations());
        } catch(EnvironmentNotFoundException e) {
            System.err.println("Database is currently empty!!.");
            return;
        }
    }

    public AstToken getSEMI () {
        
        return (AstToken) tok [1] ;
    }

    public AstToken getSHOW () {
        
        return (AstToken) tok [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {true, true} ;
    }

    public ShowDb setParms (AstToken tok0, AstToken tok1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        tok [0] = tok0 ;            /* SHOW */
        tok [1] = tok1 ;            /* SEMI */
        
        InitChildren () ;
        return (ShowDb) this ;
    }

}
