// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

abstract public class SqlLang extends AstNode {

    public void execute () {
        
        super.execute();
    }

}
