#!/bin/sh
rm -rf mdb/don/*
cd mdb
javac -cp jakarta.jar:je-5.0.103.jar src/mdb/*.java src/minidb/models/*.java src/minidb/je/*.java
time java -cp jakarta.jar:je-5.0.103.jar:src mdb.Main -create don/mdb.database -f ../tests/test2.sql
