#!/bin/sh
rm -rf mdb/JEDB/*
cd mdb
javac -cp jakarta.jar:je-5.0.103.jar src/mdb/*.java src/minidb/models/*.java src/minidb/je/*.java
java -cp jakarta.jar:je-5.0.103.jar:src mdb.Main -f ../tests/ddltest.sql
java -cp jakarta.jar:je-5.0.103.jar:src mdb.Main -f ../tests/dmltest.sql
