// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class Asgn extends Assign {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 1 ;

    public void execute () {
        
        super.execute();
    }

    public AstToken getEQ () {
        
        return (AstToken) tok [0] ;
    }

    public Field_name getField_name () {
        
        return (Field_name) arg [0] ;
    }

    public Literal getLiteral () {
        
        return (Literal) arg [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, true, false} ;
    }

    public Asgn setParms (Field_name arg0, AstToken tok0, Literal arg1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* Field_name */
        tok [0] = tok0 ;            /* EQ */
        arg [1] = arg1 ;            /* Literal */
        
        InitChildren () ;
        return (Asgn) this ;
    }

}
