/* Generated By:JavaCC: Do not edit this line. BaliParserConstants.java */
package mdb ;

public interface BaliParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int LETTER = 13;
  int DIGIT = 14;
  int ABORT = 15;
  int ALL = 16;
  int AND = 17;
  int BANG = 18;
  int CLOSE = 19;
  int COMMA = 20;
  int COMMIT = 21;
  int CREATE = 22;
  int DELETE = 23;
  int DIV = 24;
  int DOT = 25;
  int EQ = 26;
  int EXIT = 27;
  int FROM = 28;
  int GE = 29;
  int GT = 30;
  int INDEX = 31;
  int INSERT = 32;
  int INTEGER = 33;
  int INTO = 34;
  int LE = 35;
  int LOAD = 36;
  int LP = 37;
  int LT = 38;
  int OPEN = 39;
  int RP = 40;
  int SCRIPT = 41;
  int SELECT = 42;
  int SEMI = 43;
  int SET = 44;
  int SHOW = 45;
  int STRING = 46;
  int TABLE = 47;
  int UPDATE = 48;
  int VALUES = 49;
  int WHERE = 50;
  int STRING_LITERAL = 51;
  int INTEGER_LITERAL = 52;
  int IDENTIFIER = 53;
  int OTHER = 54;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<LETTER>",
    "<DIGIT>",
    "\"abort\"",
    "\"*\"",
    "\"and\"",
    "\"!\"",
    "\"close\"",
    "\",\"",
    "\"commit\"",
    "\"create\"",
    "\"delete\"",
    "\"/\"",
    "\".\"",
    "\"=\"",
    "\"exit\"",
    "\"from\"",
    "\">=\"",
    "\">\"",
    "\"index\"",
    "\"insert\"",
    "\"int\"",
    "\"into\"",
    "\"<=\"",
    "\"load\"",
    "\"(\"",
    "\"<\"",
    "\"open\"",
    "\")\"",
    "\"script\"",
    "\"select\"",
    "\";\"",
    "\"set\"",
    "\"show\"",
    "\"str\"",
    "\"table\"",
    "\"update\"",
    "\"values\"",
    "\"where\"",
    "<STRING_LITERAL>",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<OTHER>",
  };

}
