// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class JoinClause extends Clause {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 1 ;

    public void execute () {
        
        super.execute();
    }

    public AstToken getEQ () {
        
        return (AstToken) tok [0] ;
    }

    public Field_spec getField_spec () {
        
        return (Field_spec) arg [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, true, false} ;
    }

    public JoinClause setParms (Field_spec arg0, AstToken tok0, Field_spec arg1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* Field_spec */
        tok [0] = tok0 ;            /* EQ */
        arg [1] = arg1 ;            /* Field_spec */
        
        InitChildren () ;
        return (JoinClause) this ;
    }

}
