// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

public class One_rel_predElem extends AstListNode {

    public AstToken getAND () {
        return (AstToken) tok [0] ;
    }

    public One_rel_clause getOne_rel_clause () {
        
        return (One_rel_clause) arg [0] ;
    }

    public One_rel_predElem setParms (AstToken tok0, One_rel_clause arg0) {
        
        tok = new AstToken [1] ;
        tok [0] = tok0 ;            /* AND */
        return setParms (arg0) ;    /* One_rel_clause */
    }

    public One_rel_predElem setParms (One_rel_clause arg0) {
        
        super.setParms (arg0) ;     /* One_rel_clause */
        return (One_rel_predElem) this ;
    }

}
