// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class OneRelClause extends One_rel_clause {

    final public static int ARG_LENGTH = 3 ;
    final public static int TOK_LENGTH = 1 /* Kludge! */ ;

    public void execute () {
        
        super.execute();
    }

    public Field_name getField_name () {
        
        return (Field_name) arg [0] ;
    }

    public Literal getLiteral () {
        
        return (Literal) arg [2] ;
    }

    public Rel getRel () {
        
        return (Rel) arg [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, false, false} ;
    }

    public OneRelClause setParms (Field_name arg0, Rel arg1, Literal arg2) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* Field_name */
        arg [1] = arg1 ;            /* Rel */
        arg [2] = arg2 ;            /* Literal */
        
        InitChildren () ;
        return (OneRelClause) this ;
    }

}
