#!/bin/sh
rm -rf mdb/don/*
cd mdb
javac -cp jakarta.jar:je-5.0.103.jar src/mdb/*.java src/minidb/models/*.java src/minidb/je/*.java
#time java -cp jakarta.jar:je-5.0.103.jar:src mdb.Main -create don/mdb.database -f ../tests1/ddltest1.sql
time java -cp jakarta.jar:je-5.0.103.jar:src mdb.Main -create don/mdb.database -f ../tests/test1.sql > result1.dat
time java -cp jakarta.jar:je-5.0.103.jar:src mdb.Main -create don/mdb.database -f ../tests/test4.sql >> result1.dat
