// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

public class Assign_listElem extends AstListNode {

    public Assign getAssign () {
        
        return (Assign) arg [0] ;
    }

    public AstToken getCOMMA () {
        return (AstToken) tok [0] ;
    }

    public Assign_listElem setParms (Assign arg0) {
        
        super.setParms (arg0) ;     /* Assign */
        return (Assign_listElem) this ;
    }

    public Assign_listElem setParms (AstToken tok0, Assign arg0) {
        
        tok = new AstToken [1] ;
        tok [0] = tok0 ;            /* COMMA */
        return setParms (arg0) ;    /* Assign */
    }

}
