// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

abstract public class Delete extends Dml_stmt {

    public void execute () {
        
        super.execute();
    }

}
