// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class FieldDecl extends Field_decl {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 1 /* Kludge! */ ;

    public void execute () {
        
        super.execute();
    }

    public Field_name getField_name () {
        
        return (Field_name) arg [0] ;
    }

    public Field_type getField_type () {
        
        return (Field_type) arg [1] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, false} ;
    }

    public FieldDecl setParms (Field_name arg0, Field_type arg1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* Field_name */
        arg [1] = arg1 ;            /* Field_type */
        
        InitChildren () ;
        return (FieldDecl) this ;
    }

}
