// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;

public class Rel_listElem extends AstListNode {

    public AstToken getCOMMA () {
        return (AstToken) tok [0] ;
    }

    public Rel_name getRel_name () {
        
        return (Rel_name) arg [0] ;
    }

    public Rel_listElem setParms (AstToken tok0, Rel_name arg0) {
        
        tok = new AstToken [1] ;
        tok [0] = tok0 ;            /* COMMA */
        return setParms (arg0) ;    /* Rel_name */
    }

    public Rel_listElem setParms (Rel_name arg0) {
        
        super.setParms (arg0) ;     /* Rel_name */
        return (Rel_listElem) this ;
    }

}
