// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package mdb;
import Jakarta.util.*;
import java.io.*;
import java.util.*;

public class RelDotField extends Rel_dot_field {

    final public static int ARG_LENGTH = 2 ;
    final public static int TOK_LENGTH = 1 ;

    public void execute () {
        
        super.execute();
    }

    public AstToken getDOT () {
        
        return (AstToken) tok [0] ;
    }

    public Field_name getField_name () {
        
        return (Field_name) arg [1] ;
    }

    public Rel_name getRel_name () {
        
        return (Rel_name) arg [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, true, false} ;
    }

    public RelDotField setParms (Rel_name arg0, AstToken tok0, Field_name arg1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* Rel_name */
        tok [0] = tok0 ;            /* DOT */
        arg [1] = arg1 ;            /* Field_name */
        
        InitChildren () ;
        return (RelDotField) this ;
    }

}
